package com.expediagroup.sdk.core.logging.mask

import com.ebay.ejmask.extenstion.builder.json.JsonFieldPatternBuilder
import com.expediagroup.sdk.core.constant.LoggingMessage.OMITTED

/**
 * A builder class for creating JSON field replacement patterns specifically for Expedia Group.
 *
 * This class extends the `JsonFieldPatternBuilder` and provides an implementation for building
 * replacement patterns for JSON field masking.
 *
 * The replacement pattern format generated by this builder is structured to conceal sensitive
 * data while keeping a specified number of characters visible.
 */
internal class ExpediaGroupJsonFieldPatternBuilder : JsonFieldPatternBuilder() {
    override fun buildReplacement(visibleCharacters: Int, vararg fieldNames: String?): String = "\"$1$2$OMITTED\""
}
