name: Code Quality Checks
on: pull_request

jobs:
  unit-test-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 21
      - name: Pull GraphQL Submodule
        run: ./scripts/graphql/init.sh
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Run Checks
        id: build
        run: gradle clean build
      - name: Upload Coverage Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: code/build/reports/kover
