name: Deploy Reference Documentation

on:
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  deploy-reference-docs:
    uses: "ExpediaGroup/expediagroup-java-sdk/.github/workflows/generate-ref-docs.yaml@main"
    with:
      buildsystem: 'gradle'
      ref: ${{ inputs.ref != '' && inputs.ref || github.ref }}
    secrets:
      GITHUB_PAT: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
