name: PR Checks
on: pull_request

jobs:
  unit-tests-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 8
      - uses: gradle/actions/setup-gradle@v4
      - run: gradle clean build
      - working-directory: code
        run: gradle clean build
