name: PR Checks
on: pull_request

jobs:
  unit-tests-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 21
      - name: Pull GraphQL Submodule
        run: ./scripts/graphql/init.sh
      - name: Build Project & Run Unit-Tests
        uses: gradle/actions/setup-gradle@v4
      - run: gradle clean build
