name: PR Checks
on: pull_request

jobs:
  unit-tests-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'coretto'
          java-version: 8
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build with Gradle
        working-directory: code
        run: gradle clean build
